name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: recursive
      - run: npm install
      - run: cd themes
      - run: git clone https://github.com/google/docsy
      - run: git submodule update --init --recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.3'
          extended: true

      - name: Build
        run: hugo 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public



      # - name: Build Site
      #   uses: chabad360/hugo-actions@master
      #   with:
      #     hugoVersion: extended_0.58.3
      #     args: --cleanDestinationDir
      #
      # - name: Publish Site
      #   uses: chabad360/hugo-gh-pages@master
      #   with:
      #     githubToken: ${{ secrets.PERSONAL_TOKEN }}
      #     hugoVersion: extended_0.58.3
      #     args: --cleanDestinationDir
