name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: recursive
      - run: npm install
      - run: cd themes
      - run: git clone https://github.com/google/docsy
      - run: git submodule update --init --recursive
      - name: Build Site
        uses: chabad360/hugo-actions@master

      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.PERSONAL_TOKEN }}
          hugoVersion: extended_0.58.3
          args: --cleanDestinationDir
