name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'extended_0.58.3'

      - name: Build
      run: hugo

 - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
    
