name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.75.1'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public



      # - name: Build Site
      #   uses: chabad360/hugo-actions@master
      #   with:
      #     hugoVersion: extended_0.58.3
      #     args: --cleanDestinationDir
      #
      # - name: Publish Site
      #   uses: chabad360/hugo-gh-pages@master
      #   with:
      #     githubToken: ${{ secrets.PERSONAL_TOKEN }}
      #     hugoVersion: extended_0.58.3
      #     args: --cleanDestinationDir
